In [1]:
import numpy as np
a=np.array([1,2,3])
print(a)

[1 2 3]


In [2]:
b=np.array([(1,2,3),(3,4,5)])
print(b)

[[1 2 3]
 [3 4 5]]


In [4]:
array=np.array([(1,2,3,4), (5,6,7,8)], dtype=np.int64)
print(array)

[[1 2 3 4]
 [5 6 7 8]]


In [5]:
import sys
S=range(1000)
print(sys.getsizeof(5)*len(S))

28000


In [7]:
D=np.arange(1000)
print(D.size*D.itemsize)

8000


In [8]:
import time
SIZE = 1000000

L1 = range(SIZE)
L2 = range(SIZE)

start= time.time()
result= [(x,y) for x,y in zip(L1,L2)] # Se usa for 
print((time.time()-start)*1000) # Velocidad de NUMPY


402.20165252685547


In [9]:
A1 = np.arange(SIZE)
A2 = np.arange(SIZE)

start = time.time()
result = A1 + A2                # Solo se suma
print((time.time()-start)*1000) # Velocidad de NUMPY

79.10728454589844


In [4]:
import numpy as np
# Crear una matriz de unos - 3 filas y 4 columnas
unos = np.ones((3,4)) 
print(unos)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [5]:
# Crear una matriz de ceros - 3 filas y 4 columnas
ceros = np.zeros((3,4))
print(ceros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [6]:
# Crear una matriz con valores aleatorios
aleatorios = np.random.random((2,2))
print(aleatorios)

[[0.72896994 0.07391023]
 [0.45694179 0.58356663]]


In [12]:
# Crear una matriz vacia 
vacia = np.empty((3,2))
print(vacia)

[[1.94494243e-316 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000]]


In [14]:
# Crear una matriz de un solo valor
full = np.full((2,2),7)
print(full)

[[7 7]
 [7 7]]


In [15]:
# Crear una matriz con valores espaciados uniformemente
espacio1 = np.arange(0,30,5)
print(espacio1)


[ 0  5 10 15 20 25]


In [17]:
 espacio2 = np.linspace(0,2,5)
print(espacio2)

[0.  0.5 1.  1.5 2. ]


In [18]:
# Crear una matriz identidad
identidad1 = np.eye(4,4)
print(identidad1)

identidad2 = np.identity(4)
print(identidad2)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [19]:
# Conocer las dimenciones de una matriz 
a = np.array([(1,2,3),(4,5,6)])
print(a.ndim)

2


In [20]:
# Conocer el tipo de datos
print(a.dtype)

int64


In [21]:
# Conocer el tamano de una matriz
a = np.array([(1,2,3,4,5,6)])
print(a.size)
print(a.shape)

6
(1, 6)


In [25]:
# Extraer un solo valor de la matriz - el valor ubicado en la fila 0 columna 2
a = np.array([(1,2,3,4), (5,6,7,8)])
print(a[0,2])

3


In [26]:
# Extraer todos los valores de todas las filas ubicadas en la columna 3
a = np.array([(1,2,3,4), (5,6,7,8)])
print(a[0:,2])

[3 7]


In [27]:
# Encontrar el minimo, maximo y la suma 
a = np.array([2,45,800])
print(a.min())
print(a.max())
print(a.sum())

2
800
847


In [28]:
# Calcular la raiz cuadrada y l adesviacion estandar
a = np.array([(1,4,81),(33,44,50)])
print(np.sqrt(a))
print(np.std(a))

[[1.         2.         9.        ]
 [5.74456265 6.63324958 7.07106781]]
27.5121185419565


In [29]:
# Calcular la suma, resta, multiplicacion, y division de dos matrices
x = np.array([(1,2,3),(3,4,5)])
y = np.array([(1,2,3),(3,4,5)])
print(x+y)
print()
print(x-y)
print()
print(x*y)
print()
print(x/y)

[[ 2  4  6]
 [ 6  8 10]]

[[0 0 0]
 [0 0 0]]

[[ 1  4  9]
 [ 9 16 25]]

[[1. 1. 1.]
 [1. 1. 1.]]
